#!/usr/bin/env python

from sys import stdin, stdout, argv
from json import load, dump

context = load(stdin)

with open(argv[1]) as stream:
    template = stream.read()

stdout.write(template.format(**context))
stdout.flush()
