#!/usr/bin/env python

from sys import stdin, stdout, argv
from json import load, dump
from os import makedirs
from os.path import dirname

context = load(stdin)

args = argv[1:]

try:
    index = args.index('-f')
except ValueError:
    with open(args[0]) as stream:
        template = stream.read()
else:
    template = args[index+1]
    args[index:index+2] = ()

# 
# try:
#     index = args.index('-o')
# except ValueError:
#     output = None
# else:
#     output = args[index+1]
#     args[index:index+2] = ()

text = template.format(**context)

# if output:
#     filename = output.format(**context)
#     path = dirname(filename)
#     makedirs(path, exist_ok=True)
#     with open(filename, 'w') as stream:
#         stream.write(text)
# else:
stdout.write(text)
stdout.flush()
